name = "Red Siren"
description = "Musical instrument"
authors = ["a.nvlkv <a.nvlkv@protonmail.ch>"]
repository = "https://github.com/anvlkv/red-siren"

[cores.app_core]
source = "app_core"
type_gen = "typegen"
crux_version = "0.6.3"

[cores.aucore]
source = "aucore"
type_gen = "typegen"
crux_version = "0.6.3"

[shells.android]
template = "Android"
source = "Android"
cores = ["app_core", "aucore"]

[shells.web_leptos]
template = "web-leptos"
source = "web-leptos"
cores = ["app_core", "aucore"]

[shells.iOS]
template = "iOS"
source = "iOS"
cores = ["app_core", "aucore"]
